/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/final_model.glb --transform --types --keepnames 
Files: public/final_model.glb [55.32MB] > C:\Users\Ricardo\Documents\GitHub\react-three-fiber-test\react-three-fiber-test\final_model-transformed.glb [3.98MB] (93%)
*/

import * as THREE from 'three'
import { useEffect, useRef, type JSX } from 'react'
import { PositionalAudio, useAnimations, useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { CuboidCollider, RigidBody } from '@react-three/rapier'
import { useObjectInteractions } from './ObjectInteractions'
import { useFrame } from '@react-three/fiber'
import { useStore } from './store'
import { useShallow } from 'zustand/react/shallow'
//import { useControls } from 'leva'

type ActionName = 'gltf joined final pls.001' | 'gull shadowAction' | 'boat' | 'Sphere ocean shallow' | 'gull|gull|gullAction' | 'Key.002|gull|gullAction' | 'radio w radio mat' | 'paiting rocks joined' | 'floor shoji'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Cube003: THREE.Mesh
    Cube003_1: THREE.Mesh
    Cube003_2: THREE.Mesh
    Cube003_3: THREE.Mesh
    Cube003_4: THREE.Mesh
    Cube003_5: THREE.Mesh
    Cube003_6: THREE.Mesh
    Cube003_7: THREE.Mesh
    Cube003_8: THREE.Mesh
    Cube003_9: THREE.Mesh
    Cube003_10: THREE.Mesh
    Cube003_11: THREE.Mesh
    Cube003_12: THREE.Mesh
    Cube003_13: THREE.Mesh
    Cube003_14: THREE.Mesh
    Cube003_15: THREE.Mesh
    Cube003_16: THREE.Mesh
    Cube003_17: THREE.Mesh
    Cube003_18: THREE.Mesh
    Cube003_19: THREE.Mesh
    Cube003_20: THREE.Mesh
    gull_shadow: THREE.Mesh
    boat: THREE.Mesh
    Sphere_ocean_shallow: THREE.Mesh
    radio_w_radio_mat: THREE.Mesh
    IMG_20210303_043949002: THREE.Mesh
    IMG_20210303_043949002_1: THREE.Mesh
    floor_shoji: THREE.Mesh
    gull__: THREE.Mesh
  }
  materials: {
    ['concrete.003']: THREE.MeshBasicMaterial
    ['wood windowdark noise.002']: THREE.MeshBasicMaterial
    ['windows glass.002']: THREE.MeshStandardMaterial
    ['wood wals.004']: THREE.MeshBasicMaterial
    ['wood floor.002']: THREE.MeshBasicMaterial
    ['wood sofa.002']: THREE.MeshBasicMaterial
    ['Fabric.002']: THREE.MeshBasicMaterial
    ['wood table .002']: THREE.MeshBasicMaterial
    ['wood cabinet.002']: THREE.MeshBasicMaterial
    ['wood vase.002']: THREE.MeshBasicMaterial
    ['potted_plant_01_leaves.002']: THREE.MeshStandardMaterial
    ['wood framedoor.002']: THREE.MeshBasicMaterial
    ['dog house and shoji fiber.002']: THREE.MeshBasicMaterial
    ['grass big.002']: THREE.MeshBasicMaterial
    ['grass secondary.002']: THREE.MeshBasicMaterial
    ['cutouts foliage dog.002']: THREE.MeshStandardMaterial
    ['island_tree_02.002']: THREE.MeshBasicMaterial
    ['mountains.002']: THREE.MeshStandardMaterial
    ['ocean.006']: THREE.MeshStandardMaterial
    ['rocks and boat.002']: THREE.MeshStandardMaterial
    ['gull shadow']: THREE.MeshStandardMaterial
    boat: THREE.MeshBasicMaterial
    ['ocean.001']: THREE.MeshStandardMaterial
    radio: THREE.MeshBasicMaterial
    ['wood paitning']: THREE.MeshBasicMaterial
    ['paitnng glass.001']: THREE.MeshPhysicalMaterial
    ['wood floor shoji']: THREE.MeshBasicMaterial
    seagull: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

  const baseColor = new THREE.Color("rgb(255, 255, 255)");
  const highlightColor = new THREE.Color("rgba(222, 222, 222, 1)") ;
  const ambVolume = 0.8

export function Model(props: JSX.IntrinsicElements['group']) {

     const { handleIntersectionEnter, handleIntersectionExit, handlePointerChange,showCanInteractHtml, canInteractWithMesh, 
  setIsOnRaisedFloorImpl, handleMeshClick } = useObjectInteractions();

   const {showMainMenu} = useStore(useShallow((state) =>
    ({
      showMainMenu: state.showMainMenu,
    })),)

    const ambRef = useRef<THREE.PositionalAudio>(null)

  useEffect(() => {
    if (ambRef.current) {
      if(!showMainMenu){
        ambRef.current.play()
        //const helper = new PositionalAudioHelper( ambRef.current );
        //ambRef.current.add( helper );
        ambRef.current.setVolume(ambVolume)
      }
      
    else{ //is triggered on initial load
      ambRef.current.pause();
    }
  }
  }, [showMainMenu])
 
     /* leva controls
    const { boatposition, boatscale, boatrotation, oceanposition, colliderposition, colliderargs } = useControls('', {
    boatposition: {
     value: [24.146, -2.28, -49.276],
     step: 0.001,
   },
   boatrotation: {
     value: [0, 3.20, 0],
     step: 0.01,
   },
   boatscale: {
     value: [0.20, 0.20, 0.20],
     step: 0.001,
   },
    oceanposition: {
     value: [0, 0.952, 0],
     step: 0.001,
   },
   colliderargs: {
     value: [0.5, 0.5, 0.3],
     step: 0.001,
   },
    colliderposition: {
     value: [0.666, 0.8, -0.251],
     step: 0.001,
   },
   
 }) */

  const paintingRef = useRef<THREE.Mesh>(null);
  const radioRef = useRef<THREE.Mesh>(null);
  

  
  useEffect(() => {
    if (!paintingRef.current) return;

    const paintingMat = paintingRef.current.material as THREE.MeshBasicMaterial;
    paintingMat.color = canInteractWithMesh(0) ? highlightColor : baseColor;
    paintingMat.needsUpdate = true;

}, [canInteractWithMesh(0)]);

useEffect(() => {
    if (!radioRef.current) return;

    const radioMat = radioRef.current.material as THREE.MeshBasicMaterial;
    radioMat.color = canInteractWithMesh(2) ? highlightColor : baseColor;
    radioMat.needsUpdate = true;

}, [ canInteractWithMesh(2)]);
  

  const boatRef = useRef<THREE.Mesh>(null!)
  const oceanRef = useRef<THREE.Mesh>(null!)
  const oceanDarkRef = useRef<THREE.Mesh>(null!)
  const grassRef = useRef<THREE.Mesh>(null!)
  const treeRef = useRef<THREE.Mesh>(null!)
 
   const group = useRef<THREE.Group>(null)
   const { nodes, materials, animations } = useGLTF('/final_model-transformed.glb') as unknown as GLTFResult
   const { actions } = useAnimations(animations, group)
 
   //const min = 0.87
   //const max = 0.952
   //const direction = useRef(1) // 1 = up, -1 = down


 
   useFrame((state) => {
      const t = state.clock.getElapsedTime()
      //grassRef.current.rotation.z = Math.sin(t * 1.5) * 0.0005 + Math.sin(t * 2.0) * 0.0001
     grassRef.current.rotation.z = Math.sin(t * 1.5) * 0.0005 
     grassRef.current.rotation.y = Math.cos(t * 1.0) * 0.0005 
     
     treeRef.current.rotation.z = Math.sin(t * 1.5) * 0.0005
     treeRef.current.rotation.y = Math.cos(t * 1.0) * 0.0005
     /*
     if (oceanRef.current.position.y <= min) {
       direction.current = 1
     }
     if (oceanRef.current.position.y >= max) {
       direction.current = -1
     }
 
     oceanRef.current.position.y += direction.current * 0.0002 */
     oceanRef.current.rotation.y -= 0.0003
     //oceanDarkRef.current.rotation.y -= 0.00003
 
     boatRef.current.position.x -= 0.001
 

   })
 
   useEffect (() =>{
     actions['gull shadowAction']?.syncWith(actions['gull|gull|gullAction']!)
     actions['Key.002|gull|gullAction']?.play()
     actions['gull|gull|gullAction']?.play()
     actions['gull shadowAction']?.play()
     
   })

   
  return (
     <group ref={group} {...props} dispose={null}>
          <group name="Scene">
            <group name="gltf_joined_final_pls001" position={[-0.021, 1.155, -1.138]}>
              <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['concrete.003']} />
              <mesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={materials['wood windowdark noise.002']}>
                <PositionalAudio ref={ambRef} loop url="/sfx/amb-001.mp3" distance={1.5}/></mesh> 
             
              <mesh name="Cube003_2" geometry={nodes.Cube003_2.geometry} > <meshBasicMaterial
                                            depthWrite={false}  // transparency rendering without popping like deitor
                                            side={THREE.DoubleSide}  // render front and back faces
                                      transparent
                                      opacity={0.1}
                                      color="#ecebe8" //color="#ece8c3"
                                    /></mesh> 
               <RigidBody type="fixed" friction={0} restitution={0}>
              <mesh name="Cube003_3" geometry={nodes.Cube003_3.geometry} material={materials['wood wals.004']} />
              </RigidBody>
              <mesh name="Cube003_4" geometry={nodes.Cube003_4.geometry} material={materials['wood floor.002']} />
    
              <RigidBody type="fixed" friction={0} restitution={0} colliders={false}>
                  <CuboidCollider args={[0.3, 0.4, 0.25]} position={[0.005,-0.73, 1.5920000267028809]} ></CuboidCollider>
              <mesh name="Cube003_7" geometry={nodes.Cube003_7.geometry} material={materials['wood table .002']} />
                  
              </RigidBody>
               <RigidBody type="fixed" friction={0} restitution={0}>
              <mesh name="Cube003_5" geometry={nodes.Cube003_5.geometry} material={materials['wood sofa.002']} />
              </RigidBody>
              <mesh name="Cube003_6" geometry={nodes.Cube003_6.geometry} material={materials['Fabric.002']} />
              
              <RigidBody type="fixed" friction={0} restitution={0}>
              <mesh name="Cube003_8" geometry={nodes.Cube003_8.geometry} material={materials['wood cabinet.002']} />
              </RigidBody>
              
              <mesh name="Cube003_9" geometry={nodes.Cube003_9.geometry} material={materials['wood vase.002']} />
              <mesh name="Cube003_10" geometry={nodes.Cube003_10.geometry} material={materials['potted_plant_01_leaves.002']} />
    
              <RigidBody type="fixed" friction={0} restitution={0}>
              <mesh name="Cube003_11" geometry={nodes.Cube003_11.geometry} material={materials['wood framedoor.002']} />
              </RigidBody>
    
              <RigidBody type="fixed" friction={0} restitution={0} colliders={false}>
                 <CuboidCollider args={[0.11,0.98,0.59]} position={[1.09, -0.43, 3.92]} ></CuboidCollider>
                  <CuboidCollider args={[0.11,0.98,0.59]} position={[-1.09, -0.42, 3.92]} ></CuboidCollider>
                  <CuboidCollider args={[0.11,0.98,1.40]} position={[-1.31, -0.14, 1.94]} ></CuboidCollider>
              <mesh name="Cube003_12" geometry={nodes.Cube003_12.geometry} material={materials['wood framedoor.002']} />
    
              </RigidBody>
              
              <mesh name="Cube003_13" geometry={nodes.Cube003_13.geometry} material={materials['dog house and shoji fiber.002']} />
              <mesh name="Cube003_14" geometry={nodes.Cube003_14.geometry} material={materials['grass big.002']} />
              <mesh name="Cube003_15" geometry={nodes.Cube003_15.geometry} material={materials['grass secondary.002']} />
              <mesh ref={grassRef} name="Cube003_16" geometry={nodes.Cube003_16.geometry} material={materials['cutouts foliage dog.002']} />
              <mesh ref = {treeRef} name="Cube003_17" geometry={nodes.Cube003_17.geometry} material={materials['island_tree_02.002']} />
              <mesh name="Cube003_18" geometry={nodes.Cube003_18.geometry} material={materials['mountains.002']} material-depthWrite={false} />
              <mesh ref={oceanDarkRef} name="Cube003_19" geometry={nodes.Cube003_19.geometry} material={materials['ocean.006']} material-roughness={0.23}  />
              <mesh name="Cube003_20" geometry={nodes.Cube003_20.geometry} material={materials['rocks and boat.002']} />
            </group>
            <mesh name="gull_shadow" geometry={nodes.gull_shadow.geometry} material={materials['gull shadow']} position={[4.011, 0.231, -9.038]} scale={0.048} />
            <mesh ref={boatRef} name="boat" geometry={nodes.boat.geometry} material={materials.boat} position={[24.146, -2.28, -49.276]} rotation={[0, 3.20, 0]}scale={[0.20, 0.20, 0.20]} ></mesh>
            <mesh ref={oceanRef} name="Sphere_ocean_shallow" geometry={nodes.Sphere_ocean_shallow.geometry} material={materials['ocean.001']} position={[0, 0.952, 0]} rotation={[0, 1.035, 0]} scale={30} />
    
    
    
            <RigidBody type="fixed" colliders={false}>
              <CuboidCollider args={[0.64, 0.83, 0.35]} position={[0.67, 1.13, -0.25]}
                sensor onIntersectionEnter={(state) => { handleIntersectionEnter(state, 2) }}
                onIntersectionExit={(state) => { handleIntersectionExit(state, 2) }}
              ></CuboidCollider>
              <mesh ref= {radioRef} name="radio_w_radio_mat" geometry={nodes.radio_w_radio_mat.geometry} material={materials.radio} position={[0.866, 0.784, -0.922]}
                onPointerEnter={(event) => { handlePointerChange(event, 2) }}
                onPointerOut={(event) => { handlePointerChange(event, -1) }}
                onClick={(event) => { handleMeshClick(event, 2) }}
              >  {showCanInteractHtml(2)}
              </mesh>
            </RigidBody>
           
            <group name="paiting_rocks_joined" position={[-1.206, 1.314, 0.451]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.623}>
    
            <RigidBody type="fixed" friction={0} restitution={0}>
    
              <CuboidCollider args={[1.4, 0.5, 1]} position={[0.206, 0.514, 0.451]}
    
                sensor onIntersectionEnter={(state) => { handleIntersectionEnter(state, 0) }}
                onIntersectionExit={(state) => { handleIntersectionExit(state, 0) }}
    
              ></CuboidCollider>
              <mesh ref={paintingRef} name="IMG_20210303_043949002" geometry={nodes.IMG_20210303_043949002.geometry} material={materials['wood paitning']} 
               
               onPointerEnter={(event) => { handlePointerChange(event, 0) }}
              onPointerOut={(event) => { handlePointerChange(event, -1) }}
              onClick={(event)=> {handleMeshClick(event,0)}}
              >  {showCanInteractHtml(0)}
              </mesh>
              </RigidBody>
              
              {/* <mesh name="IMG_20210303_043949002_1" geometry={nodes.IMG_20210303_043949002_1.geometry} material={materials['paitnng glass.001']} > <meshBasicMaterial
        transparent
        opacity={0.1}
        color="#e8ecef"
      /></mesh> */ } 
            </group>
             <RigidBody  type="fixed"  colliders={false}>
               <CuboidCollider args={[1, 0.2, 0.7]} position={[-0.021, 0.6, 2.901]}
                
                sensor onIntersectionEnter={() => { setIsOnRaisedFloorImpl(true)}}
                onIntersectionExit={() => { setIsOnRaisedFloorImpl(false) }}
    
              ></CuboidCollider>
            <mesh name="floor_shoji" geometry={nodes.floor_shoji.geometry} material={materials['wood floor shoji']} position={[-0.021, 1.262, 2.662]} rotation={[0, Math.PI / 2, 0]} />
            </RigidBody>
            <mesh name="gull__" geometry={nodes.gull__.geometry} material={materials.seagull} morphTargetDictionary={nodes.gull__.morphTargetDictionary} morphTargetInfluences={nodes.gull__.morphTargetInfluences} position={[4.048, 0.301, -9.006]} rotation={[Math.PI, -0.883, Math.PI]} scale={0.008} />
          </group>
        </group>
      )
    }

useGLTF.preload('/final_model-transformed.glb')
