/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'
import { RigidBody } from '@react-three/rapier'


type GLTFResult = GLTF & {
  nodes: {
    cabnet_window: THREE.Mesh
    flloor: THREE.Mesh
    wall_left: THREE.Mesh
    wall_right: THREE.Mesh
    window_frame_small: THREE.Mesh
    Sofa_Top: THREE.Mesh
  }
  materials: {
    ['wood cabinet']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    concrete: THREE.MeshStandardMaterial
    ['wood wals']: THREE.MeshStandardMaterial
    ['wood walls dark noise']: THREE.MeshStandardMaterial
    Fabric: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/room-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
       
        geometry={nodes.cabnet_window.geometry}
        material={materials['wood cabinet']}
        position={[-0.0212124, 0.5623554, -0.7909549]}
        scale={[1, 0.7466829, 1]}
      />
      
      <mesh
  
        geometry={nodes.flloor.geometry}
        material={materials['Material.003']}
        position={[-0.0212126, 0.2037542, 0]}
      />
      <mesh
        
        geometry={nodes.wall_left.geometry}
        material={materials.concrete}
        position={[-1.1592056, 1.0657611, 0]}
      />
      <mesh
        
        geometry={nodes.wall_right.geometry}
        material={materials['wood wals']}
        position={[1.1167808, 1.0657611, 0]}
      />
      <mesh
      
        geometry={nodes.window_frame_small.geometry}
        material={materials['wood walls dark noise']}
        position={[-0.0212124, 1.2447398, -1.1258256]}
        scale={[1.5885029, 0.8518716, 1.6468179]}
      />
       <RigidBody type="fixed" friction={0} restitution={0}>
      <mesh
        
        geometry={nodes.Sofa_Top.geometry}
        material={materials.Fabric}
        position={[0.8561146, 0.6755307, 0.4489174]}
        rotation={[-0.0000993, -0.002277, 1.2228477]}
        scale={[1.4277905, 1.0302796, 0.8491176]}
      />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/room-transformed.glb')