/* a fake shadow model,the outside grass big and secondaryy duplicated an raised up a bit. 
not that better than the old shadow plane, and despite affecting fences, z fighting 


Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/shadow_text_decal.glb --transform --types --keepnames 
Files: public/shadow_text_decal.glb [309.66KB] > C:\Users\Ricardo\Documents\GitHub\react-three-fiber-test\react-three-fiber-test\shadow_text_decal-transformed.glb [65.96KB] (79%)
*/

import * as THREE from 'three'
import {  type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    gltf_joined_final_pls002: THREE.Mesh
  }
  materials: {
    shadowTex: THREE.MeshStandardMaterial
  }
  animations: []
}

export function FakeShadow(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/shadow_text_decal-transformed.glb') as unknown as GLTFResult
    const tex = materials['shadowTex'].map
    useFrame((_,) => {
       if (tex) {
      tex.offset.x -= 0.0001
      tex.offset.y += 0.0001
    }
    })
  return (
    <group {...props} dispose={null}>
      <mesh name="gltf_joined_final_pls002" geometry={nodes.gltf_joined_final_pls002.geometry} material={materials.shadowTex} position={[-0.021, 1.158, -1.138]} />
    </group>
  )
}

useGLTF.preload('/shadow_text_decal-transformed.glb')
