/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/shadow_text_decal.glb --transform --types --keepnames 
Files: public/shadow_text_decal.glb [309.66KB] > C:\Users\Ricardo\Documents\GitHub\react-three-fiber-test\react-three-fiber-test\shadow_text_decal-transformed.glb [65.96KB] (79%)
*/

import * as THREE from 'three'
import { useEffect, useRef, type JSX } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { CuboidCollider, RigidBody } from '@react-three/rapier'
import { Select } from '@react-three/postprocessing'
import { useObjectInteractions } from './ObjectInteractions'
import { useFrame } from '@react-three/fiber'
import { useControls } from 'leva'

type GLTFResult = GLTF & {
  nodes: {
    gltf_joined_final_pls002: THREE.Mesh
  }
  materials: {
    shadowTex: THREE.MeshStandardMaterial
  }
  animations: []
}

export function FakeShadow(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/shadow_text_decal-transformed.glb') as unknown as GLTFResult
    const tex = materials['shadowTex'].map
    useFrame((_,) => {
       if (tex) {
      tex.offset.x -= 0.004
      tex.offset.y += 0.005
    }
    })
  return (
    <group {...props} dispose={null}>
      <mesh name="gltf_joined_final_pls002" geometry={nodes.gltf_joined_final_pls002.geometry} material={materials.shadowTex} position={[-0.021, 1.158, -1.138]} />
    </group>
  )
}

useGLTF.preload('/shadow_text_decal-transformed.glb')
