/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/skydome_only.glb --transform --resolution 4096 --types --keepnames 
Files: public/skydome_only.glb [7.86MB] > C:\Users\Ricardo\Documents\GitHub\react-three-fiber-test\react-three-fiber-test\skydome_only-transformed.glb [240.03KB] (97%)
*/
// so it preserves 4k text when transformed
import * as THREE from 'three'
import { useEffect, useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Sphere_skydome001: THREE.Mesh
  }
  materials: {
    msdasfa: THREE.MeshStandardMaterial
  }
  animations: []
}

export function Skydome(props: JSX.IntrinsicElements['group']) {
  const skydomeRef = useRef<THREE.Mesh>(null!)
  
    useFrame((_,) => {
      skydomeRef.current.rotation.y += 0.00004
    })
  const { nodes, materials } = useGLTF('/skydome_only-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh ref={skydomeRef} name="Sphere_skydome001" geometry={nodes.Sphere_skydome001.geometry} material={materials.msdasfa} position={[0, 0.583, 0]} rotation={[Math.PI, 1.347, 0]} scale={63.006} />
    </group>
  )
}

useGLTF.preload('/skydome_only-transformed.glb')
