/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/testing_dim_wpaiting.glb --transform --types 
Files: public/testing_dim_wpaiting.glb [66.64MB] > C:\Users\Ricardo\Documents\GitHub\react-three-fiber-test\react-three-fiber-test\testing_dim_wpaiting-transformed.glb [1.15MB] (98%)
*/

import * as THREE from 'three'
import { useEffect, useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { CuboidCollider, RigidBody } from '@react-three/rapier'
import { Select } from '@react-three/postprocessing'
import { useObjectInteractions } from './ObjectInteractions'

type ActionName = 'flloor' | 'wall left' | 'wall right' | 'wall window.001' | 'paiting rocks frame' | 'paiting rocks glass' | 'wall door l frame fabric only' | 'wall door l frame fabric only.001' | 'wall door' | 'strucutrer wall dor old'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    flloor: THREE.Mesh
    Cube: THREE.Mesh
    Cube_1: THREE.Mesh
    Cube001: THREE.Mesh
    Cube001_1: THREE.Mesh
    Cube008: THREE.Mesh
    Cube008_1: THREE.Mesh
    paiting_rocks_frame: THREE.Mesh
    paiting_rocks_glass: THREE.Mesh
    Cube025: THREE.Mesh
    Cube025_1: THREE.Mesh
    Cube030: THREE.Mesh
    Cube030_1: THREE.Mesh
    Cube012: THREE.Mesh
    Cube012_1: THREE.Mesh
    Cube022: THREE.Mesh
    Cube022_1: THREE.Mesh
  }
  materials: {
    ['wood floor']: THREE.MeshStandardMaterial
    concrete: THREE.MeshStandardMaterial
    ['wood wals.002']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['wood wals']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['wood table sofa']: THREE.MeshStandardMaterial
    ['wood walls dark noise']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {

  // -1 = none , 0 = paitnng , 1 = sketchbook, 2= radio

  const { handleIntersectionEnter, handleIntersectionExit, handlePointerChange,showCanInteractHtml, canInteractWithMesh, 
    emissiveHighlightColor, emissiveHighlightIntensity,  setIsOnRaisedFloorImpl, handleMeshClick } = useObjectInteractions();

    /* const mat = ref.material as THREE.MeshStandardMaterial;
            mat.emissive = emissiveHighlightColor;
            mat.emissiveIntensity = canInteractWithMesh(0) ? 1 : 0;*/
    const paintingRef = useRef<THREE.Mesh>(null);

       useEffect(() => {
           if (!paintingRef.current) return
   
           const mat = paintingRef.current.material as THREE.MeshStandardMaterial
   
           mat.emissive = emissiveHighlightColor;
           mat.emissiveIntensity = canInteractWithMesh(0) ? 0.5  : 0
   
       }, [canInteractWithMesh(0)])

  const { nodes, materials } = useGLTF('/testing_dim_wpaiting-transformed.glb') as unknown as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="flloor" geometry={nodes.flloor.geometry} material={materials['wood floor']} position={[-0.021, 0.204, 0]} />
        <group name="wall_left" position={[-1.359, 1.066, 0]}>
          <RigidBody type="fixed" friction={0} restitution={0}>
            <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.concrete} />
            <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={nodes.Cube_1.material} />
          </RigidBody>
        </group>
        <group name="wall_right" position={[1.317, 1.066, 0]}>
          <RigidBody type="fixed" friction={0} restitution={0}>
            <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['wood wals.002']} />
            <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.Material} />
          </RigidBody>
        </group>
        <group name="wall_window001" position={[-0.021, 1.155, -1.138]}>
          <RigidBody type="fixed" friction={0} restitution={0}>
            <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.concrete} />
            <mesh name="Cube008_1" geometry={nodes.Cube008_1.geometry} material={nodes.Cube008_1.material} />
          </RigidBody>
        </group>
        <RigidBody type="fixed" friction={0} restitution={0}>

          <CuboidCollider args={[0.7, 0.1, 1]} position={[-1.206, 1.314, 0.451]}

            sensor onIntersectionEnter={(state) => { handleIntersectionEnter(state, 0) }}
            onIntersectionExit={(state) => { handleIntersectionExit(state, 0) }}

          ></CuboidCollider>

          <mesh name="paiting_rocks_frame" geometry={nodes.paiting_rocks_frame.geometry} material={materials['wood wals']} position={[-1.206, 1.314, 0.451]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.623}
          >
            {showCanInteractHtml(0)}
            {/*isInteracting && !isCameraAnimating && showIsInteractingHtml()*/}

          </mesh>
        </RigidBody>

        <mesh name="paiting_rocks_glass" geometry={nodes.paiting_rocks_glass.geometry} material={materials['Material.007']} position={[-1.206, 1.314, 0.451]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.623}

          onPointerEnter={(event) => { handlePointerChange(event, 0) }}
          onPointerOut={(event) => { handlePointerChange(event, -1) }}
          onClick={(event)=> {handleMeshClick(event,0)}}
          ref={paintingRef}

        />
        <group name="wall_door_l_frame_fabric_only" position={[0.463, 1.167, 3.353]} rotation={[0, Math.PI / 2, 0]} scale={[1, 0.891, 1.017]}>
          <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials['wood table sofa']} />
          <mesh name="Cube025_1" geometry={nodes.Cube025_1.geometry} material={materials['wood walls dark noise']} />
        </group>
        <group name="wall_door_l_frame_fabric_only001" position={[-0.498, 1.167, 3.34]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[-1, -0.891, -1.017]}>
          <mesh name="Cube030" geometry={nodes.Cube030.geometry} material={materials['wood table sofa']} />
          <mesh name="Cube030_1" geometry={nodes.Cube030_1.geometry} material={materials['wood walls dark noise']} />
        </group>
        <group name="wall_door" position={[-0.021, 1.262, 3.118]} rotation={[0, Math.PI / 2, 0]} scale={[1, 1, 1.017]}>
          <RigidBody type="fixed" friction={0} restitution={0}>
            <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials.concrete} />
            <mesh name="Cube012_1" geometry={nodes.Cube012_1.geometry} material={materials['wood wals']} />
          </RigidBody>
        </group>
        <group name="strucutrer_wall_dor_old" position={[-0.021, 1.262, 2.662]} rotation={[0, Math.PI / 2, 0]} scale={[1, 1, 1.09]}>
          <RigidBody type="fixed" friction={0} restitution={0}

            sensor onIntersectionEnter={() => { setIsOnRaisedFloorImpl(true)}}
            onIntersectionExit={() => { setIsOnRaisedFloorImpl(false) }}

          >
            <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials.concrete} />
            <mesh name="Cube022_1" geometry={nodes.Cube022_1.geometry} material={materials['wood floor']} />
          </RigidBody>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/testing_dim_wpaiting-transformed.glb')
