/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/tree_spha1.glb --transform --types --keepnames 
Files: public/tree_spha1.glb [37.84MB] > C:\Users\Ricardo\Documents\GitHub\react-three-fiber-test\react-three-fiber-test\tree_spha1-transformed.glb [3.09MB] (92%)
*/

import * as THREE from 'three'
import { useEffect, useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { CuboidCollider, RigidBody } from '@react-three/rapier'
import { Select } from '@react-three/postprocessing'
import { useObjectInteractions } from './ObjectInteractions'
import { useFrame } from '@react-three/fiber'
type GLTFResult = GLTF & {
  nodes: {
    Cube014: THREE.Mesh
    Cube014_1: THREE.Mesh
    Cube014_2: THREE.Mesh
    Cube014_3: THREE.Mesh
    Cube014_4: THREE.Mesh
    Cube014_5: THREE.Mesh
    Cube014_6: THREE.Mesh
    Cube014_7: THREE.Mesh
    Cube014_8: THREE.Mesh
    Cube014_9: THREE.Mesh
    Cube014_10: THREE.Mesh
    Landscape001_1: THREE.Mesh
    Landscape001_2: THREE.Mesh
    Landscape001_3: THREE.Mesh
    Landscape001_4: THREE.Mesh
    Landscape001_5: THREE.Mesh
    Landscape001_6: THREE.Mesh
    Sphere: THREE.Mesh
    shadow_plane_2: THREE.Mesh
    ocean: THREE.Mesh
  }
  materials: {
    ['wood table ']: THREE.MeshBasicMaterial
    ['wood cabinet']: THREE.MeshBasicMaterial
    ['wood floor']: THREE.MeshBasicMaterial
    ['concrete.001']: THREE.MeshBasicMaterial
    ['wood wals.002']: THREE.MeshBasicMaterial
    Material: THREE.MeshStandardMaterial
    ['windows glass']: THREE.MeshPhysicalMaterial
    ['wood floor.001']: THREE.MeshBasicMaterial
    ['wood light window']: THREE.MeshBasicMaterial
    ['wood framedoor']: THREE.MeshBasicMaterial
    ['grass big']: THREE.MeshBasicMaterial
    ['dog house tobe baked to shoji']: THREE.MeshBasicMaterial
    island_tree_02_leaves: THREE.MeshBasicMaterial
    island_tree_02_branches: THREE.MeshBasicMaterial
    fence: THREE.MeshBasicMaterial
    ['Dog-PNG-3']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['shadow.001']: THREE.MeshStandardMaterial
    ocean: THREE.MeshStandardMaterial
  }
  animations: []
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/tree_spha1-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="table" position={[-0.021, 0.601, 0.45]}>
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['wood table ']} />
        <mesh name="Cube014_1" geometry={nodes.Cube014_1.geometry} material={materials['wood cabinet']} />
        <mesh name="Cube014_2" geometry={nodes.Cube014_2.geometry} material={materials['wood floor']} />
        <mesh name="Cube014_3" geometry={nodes.Cube014_3.geometry} material={nodes.Cube014_3.material} />
        <mesh name="Cube014_4" geometry={nodes.Cube014_4.geometry} material={materials['concrete.001']} />
        <mesh name="Cube014_5" geometry={nodes.Cube014_5.geometry} material={materials['wood wals.002']} />
        <mesh name="Cube014_6" geometry={nodes.Cube014_6.geometry} material={materials.Material} />
        <mesh name="Cube014_7" geometry={nodes.Cube014_7.geometry}> <meshBasicMaterial
    transparent
    opacity={0.4}
    color="#ffffff"
  /></mesh> 
        <mesh name="Cube014_8" geometry={nodes.Cube014_8.geometry} material={materials['wood floor.001']} />
        <mesh name="Cube014_9" geometry={nodes.Cube014_9.geometry} material={materials['wood light window']} />
        <mesh name="Cube014_10" geometry={nodes.Cube014_10.geometry} material={materials['wood framedoor']} />
      </group>
      <group name="Landscape001" position={[0, 0.183, -6.489]}>
        <mesh name="Landscape001_1" geometry={nodes.Landscape001_1.geometry} material={materials['grass big']} />
        <mesh name="Landscape001_2" geometry={nodes.Landscape001_2.geometry} material={materials['dog house tobe baked to shoji']} />
        <mesh name="Landscape001_3" geometry={nodes.Landscape001_3.geometry} material={materials.island_tree_02_leaves} />
        <mesh name="Landscape001_4" geometry={nodes.Landscape001_4.geometry} material={materials.island_tree_02_branches} />
        <mesh name="Landscape001_5" geometry={nodes.Landscape001_5.geometry} material={materials.fence} />
        <mesh name="Landscape001_6" geometry={nodes.Landscape001_6.geometry} material={materials['Dog-PNG-3']} />
      </group>
      <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['Material.001']} position={[0, 0.62, 0]} rotation={[-Math.PI, 0.828, -Math.PI]} scale={63.006} />
      <mesh name="shadow_plane_2" geometry={nodes.shadow_plane_2.geometry} material={materials['shadow.001']} position={[0, 0.491, -4.887]} scale={[7.538, 3.249, 3.249]} />
      <mesh name="ocean" geometry={nodes.ocean.geometry} material={materials.ocean} position={[0, -0.269, -12.835]} scale={[13.371, 1, 6.698]} />
    </group>
  )
}

useGLTF.preload('/tree_spha1-transformed.glb')
