/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/room.glb --transform --simplify 
Files: public/room.glb [16.41MB] > C:\Users\Ricardo\Documents\GitHub\react-three-fiber-test\react-three-fiber-test\room-transformed.glb [772.98KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cabnet_window.geometry} material={materials['wood cabinet']} position={[-0.021, 0.562, -0.791]} scale={[1, 0.747, 1]} />
      <mesh geometry={nodes.flloor.geometry} material={materials['Material.003']} position={[-0.021, 0.204, 0]} />
      <mesh geometry={nodes.wall_left.geometry} material={materials.concrete} position={[-1.159, 1.066, 0]} />
      <mesh geometry={nodes.wall_right.geometry} material={materials['wood wals']} position={[1.117, 1.066, 0]} />
      <mesh geometry={nodes.window_frame_small.geometry} material={materials['wood walls dark noise']} position={[-0.021, 1.245, -1.126]} scale={[1.589, 0.852, 1.647]} />
      <mesh geometry={nodes.Sofa_Top.geometry} material={materials.Fabric} position={[0.856, 0.676, 0.449]} rotation={[0, -0.002, 1.223]} scale={[1.428, 1.03, 0.849]} />
    </group>
  )
}

useGLTF.preload('/room-transformed.glb')
